# -*- org-html-postamble-format:(("en" "<p class="author">Author: %a</p> <p>Made on
# emacs org-mode with <a href="https://jessekelly881-rethink.surge.sh/">Rethink</a></p>"));
# org-html-postamble: t -*-
#
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="/chrome/rethink.css" />
#+OPTIONS: toc:nil num:nil html-style:nil
# #+INFOJS_OPT: view:info toc:nil path:chrome/org-info.js
#+AUTHOR: Jörg Kollmann
#+TITLE: Writing pipeline commands in Eshell
#+DATE: 2026-01-12

* Experimenting with Eshell

Over the holydays I finally took some time experimenting
with ~eshell~, an interesting shell implementation for emacs.
What I love most is having shell commands and lisp code together in
one place. That can be a real game-changer.
Instead of calling ~ielm~, just use eshell for
defining and calling lisp functions. And then using them in
combination with shell commands and pipelines.

For example, just being able to call
#+begin_src shell
$ dired .
#+end_src
(unfortunately, the path argument is not optional)
or just
#+begin_src shell
$ magit
#+end_src
in the
current directory is really convenient. In fact, I'm using ~dired~
so frequently that I've defined a shortcut:
#+begin_src emacs-lisp
(defun eshell/els (&optional arg)
  (dired
   (if (null arg) "." arg)))
#+end_src
After using this, ~q~ brings you back to the eshell buffer.

Eshell has some unusual redirection functions for stdout,
like sending it to a buffer (~ls > #<buffer name>~) or to the emacs
kill ring (~ls > /dev/kill~).
An example, filtering the contents of the current directory and sending
the output to a buffer. Then, setting that buffer to dired-virtual
mode and displaying it:
#+begin_src shell
$ ls -l | grep org > #<buffer orgs>
$ (with-current-buffer (get-buffer "orgs") (dired-virtual (eshell/pwd)))
$ switch-to-buffer #<buffer orgs>
#+end_src
And instead of calling ~emacsclient my-file~, you can use the emacs
command ~find-file my-file~ (or like ~find-file-other-window~).

What I also like is being able to directly use all editing features in
the eshell buffer, or in other buffers. I'm trying to get to a workflow
having shorter command outputs directly in the shell output while sending
longer outputs to dedicated buffers.

* Writing pipeline commands for Eshell

For this, I want to have a function sending output to a buffer and setting that
buffer to ~view-mode~.
However, writing a lisp function to handle stdin and stdout in eshell
doesn't seem straightforward.
Instead I first tried to implement a virtual device for eshell.
Virtual devices are also targets for redirection, looking like a
system device (say ~/dev/null~) but only visible for eshell. Examples
for virtual targets are ~/dev/kill~ and ~/dev/clip~, which can be used
to send shell output to clipboard and kill ring.

This kind of device is declared by means of customization, like so:
#+begin_src emacs-lisp
(custom-set-variables
 '(eshell-virtual-targets
   '(("/dev/view" my-eshell-to-view-buffer t))))
#+end_src
Now, on each redirection to ~/dev/view~, eshell will call the lisp
function given here. It receives an argument giving the mode
(overwrite or append) and produces a lambda function, which will be
called repeatedly to receive the input.

I tried a quick-and-dirty implementation:
#+begin_src emacs-lisp
(defun my-eshell-to-view-buffer (mode)
  (lexical-let ((my-buffer (get-buffer-create "*viewer*")))
    (with-current-buffer my-buffer
      (view-mode 0)
      (end-of-buffer)
      (when (eq mode 'overwrite)
        (erase-buffer)))
    (lambda (string)
      (with-current-buffer my-buffer
        (view-mode 0)
        (save-excursion
          (end-of-buffer)
          (insert string))
        (view-mode t)
        (switch-to-buffer my-buffer)))))
#+end_src

Now, doing something like ~ls -al > /dev/view~ in eshell results in
another emacs buffer being opened, displayed in view-mode and showing the
text being piped in. Which is just like the more or less commands: you can scroll,
search and =q= to return to your eshell.

The last step is an alias
#+begin_src shell
alias more 'cat $1 > /dev/view'
#+end_src
and that's it! Both
#+begin_src shell
$ more my.txt
#+end_src
and
#+begin_src shell
$ ls -al | more
#+end_src
just work as
expected---nice! So I'm using the system ~cat~ command as a helper
redirecting pipe'd data into my virtual device.
Probably this can be used as a template also when
implementing other lisp commands receiving piped input.

* Piping into eshell

The other way would be piping a region into an eshell pipeline. To do
this also for non-contiguous regions (like rectangles), I'm using a
small helper:
#+begin_src emacs-lisp
(defun region-string ()
  (cl-labels
       ((nl-string (str)
          (if (string-equal (string-chop-newline str) str) (format "%s\n" str)
            str)))
     (apply #'concat
            (mapcar
             (lambda (region)
               (nl-string (buffer-substring-no-properties (car region) (cdr region))))
             (region-bounds)))))
#+end_src

The rest is easy:
#+begin_src emacs-lisp
(defun eshell/region (buffer)
  (with-current-buffer buffer (region-string)))
#+end_src
This defines a new command ~region~, receiving a buffer as
argument and outputting it's current region into the shell.
So,
#+begin_src shell
$ region #<buffer my-buffer> | grep text
#+end_src
would output the current region of
my-buffer, filtered by the grep argument (a silly example, as
you would do the filtering directly in that buffer..). But you get the
point.

A complete roundtrip of input and output pipes would be like preparing a buffer with shell commands,
selecting some of them and then calling
#+begin_src shell
$ region "shell-commands" | sh | more
#+end_src
Of course, something
similar could be done by just pressing
 =C-u M-|= in the first buffer. But again, you get the
point.

* COMMENT Local Variables
  # Local Variables:
  # org-html-htmlize-output-type: css
  # org-html-postamble-format:(("en" "<p class=\"author\">Author: %a(<a href='https://mastodon.social/@joergkb'>@joergkb</a>)</p> | <p>Made on emacs org-mode with <a href=\"https://jessekelly881-rethink.surge.sh/\">Rethink</a></p>"))
  # org-html-postamble: 't
  # org-html-preamble-format:(("en" "<img src=\"/chrome/image1.jpg\"/><div style=\"padding:2vh\"><a style=\"font-weight:900; text-decoration:none\" href=\"/\">Home</a><span style=\"float: right\">last changed: %d</span></div>"))
  # org-html-preamble: 't
  # End:
